workflow:
  as: baremetalds-ingress-node-firewall-e2e
  steps:
    allow_best_effort_post_steps: true
    allow_skip_on_success: true
    pre:
      - chain: baremetalds-ipi-pre
    test:
      - ref: baremetalds-ingress-node-firewall-e2e-test
    post:
      - chain: baremetalds-ipi-post
  documentation: |-
    This workflow executes the ingress-node-firewall end-to-end test suite on a cluster provisioned by running dev-scripts on a packet server.
